var cart = $('#cart'),                     //Varijabla za cart
    container = $('#container'),           //Varijabla za container
    programmers = $('.programmers'),       //Varijabla za sve ikone programera
    js_icons = $('.js_icons'),             //Varijabla za sve javascript ikone
    js_icon1 = $('#js_icon1'),
    js_icon2 = $('#js_icon2'),
    js_icon3 = $('#js_icon3'),
    start = $('#start_button'),            //Varijabla za button na početnoj stranici
    restart = $('#restart'),               //Varijabla za button na kraju
    score_span = $('#score'),              //Varijabla za ukupan score
    score_1 = $('#score_1'),               //Varijabla za score u cartu
    speed_span = $('#speed'),              //Varijabla za speed counter
    life_span = $('#life'),                //Varijabla za lives counter
    floor = $('#floor'),                   //Varijabla za floor (bar na dnu)
    cart_height = cart.height(),           //Varijabla za visinu carta
    container_height = container.height(),      //Varijabla za visinu containera
    js_icons_height = js_icons.height(),        //Varijabla za visinu javascript ikone
    js_icons_initial_position = parseInt(js_icons.css('top')),      //Varijabla za početnu poziciju javascript ikona (top)
    score = 0,
    life = 5,
    speed = 5,
    max_speed = 15,     //Varijabla za maksimalnu brzinu (level)
    counter = 0,
    score_updated = false,
    the_game = 0,
    anim_id = 0,
    js_icons_current_position = 0,
    js_icons_top = 0,
    cart_top = container_height - cart_height,
    fail_num = 0,
    gameover = new Audio(),
    levelup = new Audio(),
    collect = new Audio(),
    fail = new Audio(),
    background = new Audio(),
    enter = new Audio();      //Varijabla za brojač promašaja
life_span.text(life);

gameover.src = "gameover.mp3";
levelup.src = "levelup.mp3";
collect.src = "collect.mp3";
fail.src = "fail.mp3";
background.src = "background.mp3";
enter.src = "enter.mp3";